### ISSUE TITLE
IOError: [Errno 19] No such device

### ISSUE THREAD

**Issue by gdwu1427** [LCF2764/Encrypt-python-code-License-control#6]
Hi,
When I run the following script, an error occurs, can you help me solve it，thanks！
python GetHostInfo.py
Traceback (most recent call last):
  File "GetHostInfo.py", line 18, in <module>
    print(getHwAddr('eno1'))
  File "GetHostInfo.py", line 10, in getHwAddr
    info = fcntl.ioctl(s.fileno(), 0x8927, struct.pack('256s', ifname[:15]))
IOError: [Errno 19] No such device

**Comment by LCF2764** [comment]
Hi,
This appears to be an error caused by a mismatch in network card types.
Use the `ifconfig` command to see what type of network card you have, and then replace it in the `GetHostInfo.py` line16.

**Comment by gdwu1427** [comment]
Thank you, I got the MAC address by UUID to solve this problem

**Comment by LCF2764** [comment]
I've tried to get the MAC address using UUID, but in python2 and python3 the MAC address is not the same.

**Comment by gdwu1427** [comment]
The following code obtains the MAC code by UUID. The test results on python2.7 and python3.6 are the same.
`import uuid
def get_mac_address():
    node = uuid.getnode()
    mac = uuid.UUID(int = node).hex[-12:]
    return mac`
